version: '3.9'
services:
  movieapi:
    container_name: server
    restart: always
    build: .
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FLASK_APP=app.py
    volumes:
      - app:/app
  db:
    image: mongo:5
    container_name: mongodb
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=Movie
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017
    volumes:
      - mongodb:/app/data

volumes:
  mongodb:
  app: